/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdvertiseRouteImport } from './routes/advertise'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as PlacesRouteImport } from './routes/places'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as QuickPlanRouteImport } from './routes/quick-plan'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertiseRoute = AdvertiseRouteImport.update({
  id: '/advertise',
  path: '/advertise',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacesRoute = PlacesRouteImport.update({
  id: '/places',
  path: '/places',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const QuickPlanRoute = QuickPlanRouteImport.update({
  id: '/quick-plan',
  path: '/quick-plan',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/advertise': typeof AdvertiseRoute
  '/offers': typeof OffersRoute
  '/places': typeof PlacesRoute
  '/plans': typeof PlansRoute
  '/quick-plan': typeof QuickPlanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/advertise': typeof AdvertiseRoute
  '/offers': typeof OffersRoute
  '/places': typeof PlacesRoute
  '/plans': typeof PlansRoute
  '/quick-plan': typeof QuickPlanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/advertise': typeof AdvertiseRoute
  '/offers': typeof OffersRoute
  '/places': typeof PlacesRoute
  '/plans': typeof PlansRoute
  '/quick-plan': typeof QuickPlanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/advertise'
    | '/offers'
    | '/places'
    | '/plans'
    | '/quick-plan'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/advertise'
    | '/offers'
    | '/places'
    | '/plans'
    | '/quick-plan'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/advertise'
    | '/offers'
    | '/places'
    | '/plans'
    | '/quick-plan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdvertiseRoute: typeof AdvertiseRoute
  OffersRoute: typeof OffersRoute
  PlacesRoute: typeof PlacesRoute
  PlansRoute: typeof PlansRoute
  QuickPlanRoute: typeof QuickPlanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertise': {
      id: '/advertise'
      path: '/advertise'
      fullPath: '/advertise'
      preLoaderRoute: typeof AdvertiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/places': {
      id: '/places'
      path: '/places'
      fullPath: '/places'
      preLoaderRoute: typeof PlacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quick-plan': {
      id: '/quick-plan'
      path: '/quick-plan'
      fullPath: '/quick-plan'
      preLoaderRoute: typeof QuickPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdvertiseRoute: AdvertiseRoute,
  OffersRoute: OffersRoute,
  PlacesRoute: PlacesRoute,
  PlansRoute: PlansRoute,
  QuickPlanRoute: QuickPlanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
